apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beckn-service.fullname" . }}-config
  labels:
    {{- include "beckn-service.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- toYaml .Values.config | nindent 4 }}
  es-index-template.json: |
{{ .Files.Get "files/es-index-template.json" | indent 4 }}
