apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beckn-service.fullname" . }}-keyset
  labels:
    {{- include "beckn-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  subscriberId: {{ .Values.adapter.subscriberId | quote }}
  keyId: {{ .Values.credentials.keyId | quote }}
  signingPrivateKey: {{ .Values.credentials.signingPrivateKey | quote }}
  signingPublicKey: {{ .Values.credentials.signingPublicKey | quote }}
  encrPrivateKey: {{ .Values.credentials.encrPrivateKey | quote }}
  encrPublicKey: {{ .Values.credentials.encrPublicKey | quote }}
