{{- if .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beckn-service.fullname" . }}-credentials
  labels:
    {{- include "beckn-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.credentials | nindent 2 }}
{{- end }}
